[package]
name = "euler002"
version = "0.1.0"
authors = ["Marvin Smith <marvin_smith1@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "euler002"
path = "src/euler002.rs"