[package]
name = "euler003"
version = "0.1.0"
authors = ["Marvin Smith <marvin_smith1@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bv = "0.11.1"

[[bin]]
name = "euler003"
path = "src/euler003.rs"
